### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/municipal-data#105]
Without having an intimate knowledge of the data, it is difficult to understand what it means. It would be useful to link to documentation for additional context.

**Comment by jbothma** [comment]
Are you talking about the api or the scorecard?

**Comment by adieyal** [comment]
The API

**Comment by longhotsummer** [comment]
Which page in particular?

**Comment by adieyal** [comment]
I can't remember what I meant here. I'll re-open if I come across it again.
